# Coils
CL_POWER = 0
CL_Boost_MODE = 3
CL_BoostSWITCH_CTRL = 13
CL_RESET_FILTER_TIMER = 17
CL_RESET_ALARM = 18

# Holding registers
HR_MaxSPEED_MODE = 1
HR_SPEED_MODE = 2
HR_ManualSPEED = 17
HR_OPERATION_MODE = 43
HR_SetTEMP = 44

# Input registers
IR_CurSelTEMP = 0
IR_CurTEMP_SuAirIn = 1
IR_CurTEMP_SuAirOut = 2
IR_CurTEMP_ExAirIn = 3
IR_CurTEMP_ExAirOut = 4
IR_CurTEMP_Ext = 5
IR_CurTEMP_AfterPreHeater = 6
IR_CurTEMP_BeforeMainHeater = 7
IR_CurTEMP_Water = 8
IR_CurVBAT = 9
IR_CurRH_Int = 10
IR_CurRH_Ext = 11
IR_CurCO2_Int = 12
IR_CurCO2_Ext = 13
IR_CurPM25_Int = 14
IR_CurPM25_Ext = 15
IR_CurVOC_Int = 16
IR_CurVOC_Ext = 17
IR_Cur0_10V = 18
IR_CurAirFlow_Su = 19
IR_CurAirFlow_Ex = 20
IR_CurPressure_Su = 21
IR_CurPressure_Ex = 22
IR_SuRPM = 23
IR_ExRPM = 24
IR_TimerTime_01 = 25
IR_TimerTime_02 = 26
IR_FilterTime_01 = 27
IR_FilterTime_02 = 28
IR_MotorTime_01 = 29
IR_MotorTime_02 = 30
IR_StateFILTER = 31
IR_WeeklySPEED_MODE = 32
IR_WeeklySetTEMP = 33
IR_VerMAIN_FMW_start = 34
IR_VerMAIN_FMW_end = 36
IR_DeviceTYPE = 37
IR_ALARM = 38
